flags: {}
packages:
- '.'
extra-deps:
- base-prelude-1.4
- aeson-schemas-1.3.2
- opaleye-0.7.1.0
- product-profunctors-0.11.0.1
- record-dot-preprocessor-0.2.7
- record-hasfield-1.0
- servant-exceptions-0.2.1
- servant-exceptions-server-0.2.1
- stm-containers-1.2
- stm-hamt-1.2.0.4
- primitive-extras-0.8
- primitive-unlifted-0.1.3.0
- wai-middleware-metrics-0.2.4

resolver: lts-16.22
